# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version '1.109.0'

default_platform :ios

lane :beta do
  # Ensure that your git status is not dirty
  ensure_git_status_clean

  increment_build_number(xcodeproj: 'ios/ThatsCamping.xcodeproj')

  # Commit the version bump
  commit_version_bump(xcodeproj: 'ios/ThatsCamping.xcodeproj')

  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name
  add_git_tag

  # Push the new commit and tag back to your git remote
  push_to_git_remote

  # build your iOS app
  gym(
    scheme: 'ThatsCamping',
    export_method: 'app-store',
    project: 'ios/ThatsCamping.xcodeproj'
  )

  # upload to Testflight
  pilot
end
