# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version '1.109.0'

default_platform :ios

opt_out_crash_reporting

before_all do
  # Ensure that your git status is not dirty
  ensure_git_status_clean
end

lane :beta do
  set_build_number_repository(xcodeproj: 'ios/ThatsCamping.xcodeproj')

  # build your iOS app
  gym(
    scheme: 'ThatsCamping',
    export_method: 'app-store',
    project: 'ios/ThatsCamping.xcodeproj'
  )

  # upload to Testflight
  pilot
end
